---

- name: "Create and populate dotenv file"
  lineinfile:
    path: "{{ dotenv_file_path }}"
    line: "{{ item.key }}{{ dotenv_separator }}{{ item.value }}"
    state: present
    create: yes
    mode: 0600
  no_log: yes
  with_dict: "{{ dotenv_items }}"
